### ISSUE TITLE
Invalid file format for known good mp3 on transcription call

### ISSUE THREAD

**Issue by johns10** [dvcrn/ex_openai#9]
I'm attempting to upload a file for transcription.

I've tried:
* The binary from `File.read`
* The pid from `File.open`
* The path

None of these works. I'm pretty sure it wants the binary.

When I pass the binary, I get this error. However, I tried my last library, and the file format is fine. How are you calling this api? I couldn't find a test for it.

```
{:error,
 %{
   "error" => %{
     "code" => nil,
     "message" => "Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg', 'ogg', 'oga', 'flac']",
     "param" => nil,
     "type" => "invalid_request_error"
   }
 }}
```

**Comment by dvcrn** [comment]
I did a few tests and you are right, the problem is that the audio API handles files different than the Image APIs. I had assumed all of the file related endpoints work similar but I guess that's not the case

The issue stems from Elixir not retaining the file name when opening a file with File.open!, and the specific audio APIs need to know the extension of the file

The code in question is: https://github.com/dvcrn/ex_openai/blob/92aab9d76640e739b2f275ee7a7201ee70a5e118/lib/ex_openai/client.ex#L152 (notice that it doesn't have a extension when passing the filename) 

Changing this to file.wav for example makes everything work fine. 

So a couple ideas what we can do here:

- We can change the file-related endpoints to use a wrapper around File.open that retains the original filename
- We can change the file-related functions to take a path instead of a bitstring (but this means it's going to be restricted to files on disk, and no longer memory)
- Use a tuple ala `{filename, <bitstring}` (personally I like this method the most)

Let me think what the most elixir-ish way for this could be...

**Comment by dvcrn** [comment]
I went with `Use a tuple ala {filename, <bitstring} (personally I like this method the most)` and added a test for audio transcriptions. Thanks for reporting!

Could you give the latest HEAD a go and see if that works for you before I cut a release? 

API now looks like this:

```elixir
      {:ok, res} = ExOpenAI.Audio.create_transcription({"audio.wav", audio}, "whisper-1")
      assert res.text == "Hello, hello, hello, just a test."
```

**Comment by johns10** [comment]
Yes, I will get in there later, probably tomorrow (gotta go to day job now)

**Comment by johns10** [comment]
Ok, let's see how this does

**Comment by johns10** [comment]
This looks fine so far.

**Comment by johns10** [comment]
Not sure, but I may have hit another one

```
opts = [response_format: "verbose_json"]
ExOpenAI.Audio.create_transcription({"input.mp3", right_binary}, "whisper-1", opts)
```

results in

```
{:ok,
 %ExOpenAI.Components.CreateTranscriptionResponse{
   text: "This is 623-246-4213 receiving a call from 256-658-3336."
 }}
```

**Comment by dvcrn** [comment]
> Not sure, but I may have hit another one
> 
> ```
> opts = [response_format: "verbose_json"]
> ExOpenAI.Audio.create_transcription({"input.mp3", right_binary}, "whisper-1", opts)
> ```
> 
>  
> results in
> 
> ```
> {:ok,
>  %ExOpenAI.Components.CreateTranscriptionResponse{
>    text: "This is 623-246-4213 receiving a call from 256-658-3336."
>  }}
> ```

what do you mean with 'hit another one', you mean a bug? 

What is the output you are expecting from it? The transcribed text and response looks okay to me. Could you give more details what output you expected?

**Comment by francoabaroa** [comment]
Any update? @johns10
